# Site settings
title: "Arata Ishikawa"
description: > 
  Hey there! My name is Arata Ishikawa, a junior studying Engineering Physics at the University of California, Berkeley. Welcome to my personal website!
lang: en 
author: Arata Ishikawa
author_image: /assets/profile_cropped.jpg
email: iarata0120@gmail.com
linkedin_username: arata-ishikawa
github_username: arataishikawa11

baseurl:  # the subpath of your site, e.g. /blog
url: "https://arataishikawa11.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

